encoding: utf-8

title: 王鲜申's blog
email: thewangcj@gmail.com
description: 执迷不悔

baseurl: "" 
url: thewangcj.top
twitter_username: thewangcj
github_username:  thewangcj

highlighter: rouge
paginate: 4


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
excerpt_separator: <!--more-->



